### PR TITLE
Adds attribute directive.

### PR DESCRIPTION
**Pull request by JonathanPorta**
This adds an attribute directive that can be used to format the output of attributes based on their value. Currently, it only supports a naively implemented URL filter.

download

### CODE REVIEW

**Comment by kibra** [comment]
+1

:deciduous_tree:

**Comment by bensheldon** [comment]
This only checks if the entire value of the attribute is a link, right? If true, could this be improved to convert any url within the text to a link?

**Comment by JonathanPorta** [comment]
We could make it a bit smarter and it would handle your use-case well. This
should let us, in the future, just add a template if we want richer output
for any of the attributes.

**Comment by bensheldon** [comment]
Sweet! I wonder if it would be awful to implement a markdown filter with linkification. I think CommonMark has a JS lib now.

**Comment by JonathanPorta** [comment]
It would be better to do this as a directive. Filters are purely for
formatting data, not changing the DOM. To support Markdown would include
changing the DOM. But, it wouldn't be hard to write this up in a directive.

**Comment by aleszoulek** [comment]
When a value is a text, containing the link (eg `wget http://localhost/`) this will detect that as a link and take the entire value as an url (resulting in `<a href="wget http://localhost/">wget http://localhost/</a>` )

Maybe the detection function could be changed to something like: `/^https?:\/\//.match(value)`, cause when the value doesn't start with the protocol and `://` the resulting html won't make much sense anyway.

**Comment by joemiller** [comment]
that sounds reasonable. can we make it more generic so that any protocol
not just https is supported?

**Comment by aleszoulek** [comment]
`^[a-z]+:\/\/` ?

**Comment by JonathanPorta** [comment]
+1

On Tuesday, September 16, 2014, Ales Zoulek notifications@github.com
wrote:

> ^[a-z]+:\/\/ ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pantheon-systems/uchiwa/pull/1#issuecomment-55758548.

## 

Jonathan Porta

**Comment by bensheldon** [comment]
\A[a-z]+:\/\/ ?

(Does JS regex split multi lines?)

**Comment by bensheldon** [comment]
Ah, guess that's just a Ruby thing cause Ruby Regex implicitly does multiline. Javascript has a multiline flag that defaults to false.

**Pull request merged**
